
const MON="https://dqfezuahufdqxaydcayk.supabase.co/functions/v1/monitor-api",CTRL="https://dqfezuahufdqxaydcayk.supabase.co/functions/v1/moses-control";
let selectedSize=3,dp=null,activeChartMint=null,activeChartLabel=null;
const $=id=>document.getElementById(id),usd=n=>Number.isFinite(Number(n))?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(n)):"—",short=s=>s?String(s).slice(0,6)+"…"+String(s).slice(-5):"—";
const own=()=>sessionStorage.getItem("moses_owner_token")||"",sess=()=>localStorage.getItem("moses_owner_session")||"";
const hdr=()=>{const h={};if(own())h["x-moses-owner-token"]=own();if(sess())h["x-moses-owner-session"]=sess();return h};
const ago=t=>{if(!t)return"—";const s=Math.max(0,Math.floor((Date.now()-new Date(t).getTime())/1000));if(s<60)return s+"s ago";if(s<3600)return Math.floor(s/60)+"m ago";return Math.floor(s/3600)+"h ago"};
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("on"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("on"));b.classList.add("on");$(b.dataset.page).classList.add("on")});
document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{document.querySelectorAll(".chip").forEach(x=>x.classList.remove("on"));b.classList.add("on");selectedSize=Number(b.dataset.size)});
$("clearMint").onclick=()=>{$("manualMint").value="";$("manualMint").focus()};
window.copyMint=async m=>{try{await navigator.clipboard.writeText(m)}catch{}};
window.viewChart=(mint,label)=>{activeChartMint=mint;activeChartLabel=label||short(mint);if(own())loadTokenChart()};
function drawLine(id,points,key){
 const c=$(id),ctx=c&&c.getContext&&c.getContext("2d");if(!ctx)return;
 const rect=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1,w=Math.max(300,Math.floor(rect.width*dpr)),h=Math.max(160,Math.floor(rect.height*dpr));c.width=w;c.height=h;ctx.clearRect(0,0,w,h);
 const vals=(points||[]).map(x=>Number(key(x))).filter(Number.isFinite);if(vals.length<2){ctx.fillStyle="#8da197";ctx.font=(12*dpr)+"px system-ui";ctx.fillText("Not enough chart data yet",12*dpr,28*dpr);return}
 let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}const pad=18*dpr;ctx.strokeStyle="#284235";ctx.lineWidth=dpr;
 for(let i=1;i<4;i++){const y=pad+(h-2*pad)*(i/4);ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()}
 ctx.strokeStyle="#50f08a";ctx.lineWidth=2*dpr;ctx.beginPath();vals.forEach((v,i)=>{const x=pad+(w-2*pad)*(i/(vals.length-1)),y=h-pad-(h-2*pad)*((v-min)/(max-min));if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke()
}
async function loadPerformance(){
 if(!own())return;try{const d=await(await fetch(MON+"?view=performance",{cache:"no-store",headers:{"x-moses-owner-token":own()}})).json();if(!d.ok)return;const s=d.summary||{};
 $("pnlSummary").innerHTML='Realized <b class="'+(Number(s.realized_pnl_usd)>=0?'up':'down')+'">'+usd(s.realized_pnl_usd)+'</b> · Unrealized <b class="'+(Number(s.unrealized_pnl_usd)>=0?'up':'down')+'">'+usd(s.unrealized_pnl_usd)+'</b> · Net <b class="'+(Number(s.net_pnl_usd)>=0?'up':'down')+'">'+usd(s.net_pnl_usd)+'</b> · W/L '+Number(d.wins||0)+'/'+Number(d.losses||0);drawLine("pnlChart",d.points||[],x=>x.net_pnl_usd)}catch{}
}
async function loadTokenChart(){
 if(!own()||!activeChartMint)return;try{const d=await(await fetch(MON+"?view=token-chart&mint="+encodeURIComponent(activeChartMint),{cache:"no-store",headers:{"x-moses-owner-token":own()}})).json();if(!d.ok)return;const p=d.position||{},pts=d.points||[],last=pts.length?pts[pts.length-1]:null;
 $("tokenChartTitle").innerHTML='<b>'+(activeChartLabel||short(activeChartMint))+'</b> · <span class="mono">'+short(activeChartMint)+'</span>';$("tokenChartMeta").textContent='Entry '+usd(p.avg_cost_usd_per_token)+' · Current '+usd(last&&last.price_usd)+' · '+pts.length+' samples';drawLine("tokenChart",pts,x=>x.price_usd)}catch{}
}
async function refreshAll(){
 const b=$("refreshBtn");if(b)b.classList.add("spin");
 try{await portfolio();if(own()){await Promise.all([activity(),controlStatus(),loadPerformance()]);if(activeChartMint)await loadTokenChart()}}
 finally{if(b)b.classList.remove("spin")}
}
$("refreshBtn").onclick=refreshAll;

async function portfolio(){
 try{
  const d=await(await fetch(MON+"?view=portfolio&snapshot=1",{cache:"no-store"})).json();
  $("walletValue").textContent=usd(d.total_value_usd);$("solBalance").textContent=(Number(d.sol_balance)||0).toFixed(4);
  const h=d.token_holdings||[];$("livePositionCount").textContent=h.filter(x=>!["USDC","USDT"].includes(String(x.token_symbol||"").toUpperCase())).length;const tracked=h.find(x=>x.tracked_position&&!["USDC","USDT"].includes(String(x.token_symbol||"").toUpperCase()));if(tracked&&!activeChartMint){activeChartMint=tracked.mint;activeChartLabel=tracked.token_symbol||tracked.token_name||"Active position";if(own())loadTokenChart()};
  $("holdings").innerHTML=h.length?h.map(x=>{const img=x.token_image_url?'<img src="'+x.token_image_url+'" onerror="this.style.display=\\'none\\'">':'<span class="ph"></span>';const pnl=Number(x.unrealized_pnl_usd),pct=Number(x.unrealized_pnl_pct),tracked=x.tracked_position&&Number.isFinite(pnl)&&Number.isFinite(pct),cls=tracked?(pnl>0?'up':pnl<0?'down':'flat'):'flat';return '<div class="item"><div class="coin">'+img+'<div class="grow"><div class="name">'+(x.token_name||x.token_symbol||"Token")+' '+(x.token_symbol?'('+x.token_symbol+')':'')+'</div><div class="mono">'+x.mint+'</div><div class="muted">'+Number(x.amount||0).toLocaleString()+' tokens · current price '+usd(x.price_usd)+'</div></div></div>'+(tracked?'<div class="posStats"><div class="posStat"><span>Spent</span><b>'+usd(x.amount_spent_usd)+'</b></div><div class="posStat"><span>Current value</span><b>'+usd(x.current_value_usd)+'</b></div><div class="posStat"><span>P / L</span><b class="'+cls+'">'+(pnl>=0?'+':'')+usd(pnl)+'</b></div><div class="posStat"><span>Return</span><b class="'+cls+'">'+(pct>=0?'+':'')+pct.toFixed(2)+'%</b></div><div class="posStat"><span>Entry price</span><b>'+usd(x.avg_entry_price_usd)+'</b></div><div class="posStat"><span>Realized</span><b class="'+(Number(x.realized_pnl_usd)>0?'up':Number(x.realized_pnl_usd)<0?'down':'flat')+'">'+usd(x.realized_pnl_usd)+'</b></div></div>':'<div class="muted" style="margin-top:8px">Wallet holding is not currently linked to a MOSES trade position.</div>')+'<div style="display:grid;grid-template-columns:1fr 1fr;gap:7px"><button class="btn" onclick="viewChart(\\''+x.mint+'\\',\\''+String(x.token_symbol||x.token_name||"Token").replace(/'/g,"")+'\\')">View Live Chart</button><button class="btn" onclick="copyMint(\\''+x.mint+'\\')">Copy Contract</button></div></div>'}).join(""):'<div class="muted">No SPL token holdings detected.</div>';
 }catch(e){$("holdings").innerHTML='<div class="muted">Wallet feed unavailable.</div>'}
}
function renderOps(team){
 if(!team){$("opsBoard").innerHTML='<div class="muted">No team data.</div>';return}
 const order=["sniper","aaron","ezra","moses","guardian","noah"];
 $("opsBoard").innerHTML=order.map(k=>{const x=team[k]||{},active=x.last_activity&&(Date.now()-new Date(x.last_activity).getTime()<120000),err=String(x.state||"").toLowerCase().includes("fail");return '<div class="ops"><div><span class="dot '+(err?'err':active?'':'idle')+'"></span><b>'+(x.name||k.toUpperCase())+'</b><div class="muted">'+(x.role||"")+'</div></div><div>'+String(x.state||"idle")+'<div class="muted">'+ago(x.last_activity)+'</div></div><div>'+(x.target_symbol||short(x.target_mint))+'</div><div>'+String(x.detail||"—")+'</div></div>'}).join("");
}
async function activity(){
 if(!own())return;
 try{
  const d=await(await fetch(MON+"?view=activity",{cache:"no-store",headers:{"x-moses-owner-token":own()}})).json();if(!d.ok)throw new Error(d.error||"Owner unlock required");
  const c=d.config||{};$("autoState").textContent=c.autonomous_enabled?"ON":"OFF";$("autoState").style.color=c.autonomous_enabled?"var(--g)":"var(--a)";
  const st=d.trade_stats||{};$("tradeStats").innerHTML='<div><span class="muted">Live</span><b>'+(st.live_total||0)+'</b></div><div><span class="muted">Buys</span><b>'+(st.live_buys||0)+'</b></div><div><span class="muted">Sells</span><b>'+(st.live_sells||0)+'</b></div><div><span class="muted">Paper</span><b>'+(st.paper_orders||0)+'</b></div>';
  const live=d.live_trades||[];$("liveHistory").innerHTML=live.length?live.map(x=>{const rp=Number(x.realized_pnl_usd);return '<div class="item"><b>'+String(x.side||"").toUpperCase()+' '+(x.token_symbol||short(x.display_mint||x.candidate_mint))+'</b><div class="muted">'+(x.side==="buy"?('Spent '+usd(x.notional_usd)):(Number.isFinite(rp)?('Realized P/L <span class="'+(rp>=0?'up':'down')+'">'+(rp>=0?'+':'')+usd(rp)+'</span>'):'Sell'))+' · '+x.status+(x.transaction_signature?' · '+short(x.transaction_signature):'')+'</div></div>'}).join(""):'<div class="muted">No confirmed live trades.</div>';
  const paper=d.paper_orders||[];$("paperHistory").innerHTML=paper.length?paper.slice(0,12).map(x=>'<div class="item"><span class="badge paper">PAPER</span> <b>'+String(x.side||"").toUpperCase()+' '+(x.token_symbol||short(x.display_mint||x.candidate_mint))+'</b><div class="muted">'+usd(x.notional_usd)+' · '+x.status+'</div></div>').join(""):'<div class="muted">No paper tests.</div>';
  const s=d.sniper_candidates||[];$("sniperFeed").innerHTML=s.length?s.slice(0,12).map(x=>'<div class="item"><b>'+(x.symbol||short(x.mint))+'</b> <span class="badge">'+String(x.status||"watch").toUpperCase()+'</span><div class="muted">CALEB '+Number(x.sniper_score||0).toFixed(1)+' · liq '+usd(x.liquidity_usd)+' · 5m '+Number(x.price_change_5m_pct||0).toFixed(2)+'% · buys/sells '+Number(x.buys_5m||0)+'/'+Number(x.sells_5m||0)+'</div></div>').join(""):'<div class="muted">CALEB has no recent candidates.</div>';
  const a=d.aaron_recommendations||[];$("aaronFeed").innerHTML=a.length?a.slice(0,12).map(x=>'<div class="item"><b>'+(x.symbol||short(x.mint))+'</b> <span class="badge">'+String(x.status||"pending").toUpperCase()+'</span><div class="muted">AARON '+Number(x.aaron_score||0).toFixed(1)+' · risk '+Number(x.risk_score||0).toFixed(0)+' · suggested '+usd(x.suggested_notional_usd)+'</div></div>').join(""):'<div class="muted">AARON has no recent handoffs.</div>';
  const ez=d.ezra_trade_plans||[];$("ezraFeed").innerHTML=ez.length?ez.slice(0,12).map(x=>'<div class="item"><b>'+(x.symbol||short(x.mint))+'</b> <span class="badge">'+String(x.status||"approved").toUpperCase()+'</span><div class="muted">EZRA Q '+Number(x.quant_score||0).toFixed(1)+' · P(up 5m) '+(Number(x.probability_up_5m||0)*100).toFixed(1)+'% · P(up 15m) '+(Number(x.probability_up_15m||0)*100).toFixed(1)+'% · TP '+Number(x.take_profit_pct||0).toFixed(1)+'% · SL '+Number(x.hard_stop_pct||0).toFixed(1)+'% · hold '+Number(x.max_hold_minutes||0)+'m</div></div>').join(""):'<div class="muted">EZRA has no recent quantitative plans.</div>';
  const tc=d.team_status||{};renderOps(tc);$("handoff").innerHTML=['sniper','aaron','ezra','moses','guardian'].map(k=>{const x=tc[k]||{};return '<div class="row"><span><b>'+(x.name||k.toUpperCase())+'</b> <span class="typeBadge '+(x.type==="BOT"?"bot":"")+'">'+(x.type||"")+'</span><div class="muted">'+(x.role||"")+'</div></span><span style="text-align:right">'+String(x.state||"idle")+'<div class="muted">'+ago(x.last_activity)+'</div></span></div>'}).join("");
  const target=(d.positions||[]).find(x=>Number(x.token_amount_ui||0)>0)?.mint||(d.ezra_trade_plans||[]).find(x=>x.status==="active")?.mint||(d.cycles||[])[0]?.best_mint||(d.aaron_recommendations||[])[0]?.mint||(d.sniper_candidates||[])[0]?.mint||null;
  const ss=(d.sniper_candidates||[]).find(x=>!target||x.mint===target),aa=(d.aaron_recommendations||[]).find(x=>!target||x.mint===target),ee=(d.ezra_trade_plans||[]).find(x=>!target||x.mint===target),mm=(d.cycles||[]).find(x=>!target||x.best_mint===target),jj=(d.guardian_events||[]).find(x=>!target||x.mint===target);
  const steps=[['CALEB','BOT',ss?('Found '+(ss.symbol||short(ss.mint))+' · score '+Number(ss.sniper_score||0).toFixed(1)+' · liquidity '+usd(ss.liquidity_usd)):'No matching candidate'],['AARON','AI AGENT',aa?('Analysis '+Number(aa.aaron_score||0).toFixed(1)+' · risk '+Number(aa.risk_score||0).toFixed(0)+' · size '+usd(aa.suggested_notional_usd)):'No matching analyst handoff'],['EZRA','AI AGENT',ee?('Quant '+Number(ee.quant_score||0).toFixed(1)+' · P(up5) '+(Number(ee.probability_up_5m||0)*100).toFixed(1)+'% · TP '+Number(ee.take_profit_pct||0).toFixed(1)+'% · SL '+Number(ee.hard_stop_pct||0).toFixed(1)+'%'):'No matching quant plan'],['MOSES','AI AGENT',mm?('Decision '+String(mm.action_taken||mm.status||'monitoring')):'No matching execution cycle'],['JOSHUA','AI AGENT',jj?('Position '+String(jj.action||'monitor')+' · '+String(jj.trigger_type||'watching')+' · P/L '+Number(jj.pnl_pct||0).toFixed(2)+'%'):'No matching guardian action']];
  $("decisionTrace").innerHTML='<div class="muted">Target '+(target?short(target):'none')+'</div>'+steps.map(x=>'<div class="traceStep"><b>'+x[0]+' <span class="typeBadge '+(x[1]==="BOT"?"bot":"")+'">'+x[1]+'</span></b><div class="muted">'+x[2]+'</div></div>').join('');
  const nh=d.noah_health_checks||[],na=d.noah_maintenance_actions||[],latest=nh[0];if($("noahHealth")){$("noahHealth").innerHTML=latest?('<div class="row"><span><b>Overall</b><div class="muted">'+ago(latest.checked_at)+'</div></span><b class="'+(latest.overall_status==="healthy"?"healthGood":latest.overall_status==="warning"?"healthWarn":"healthBad")+'">'+String(latest.overall_status).toUpperCase()+'</b></div>'+nh.slice(0,7).map(x=>'<div class="row"><span>'+x.component+'</span><span class="'+(x.status==="healthy"?"healthGood":x.status==="warning"?"healthWarn":"healthBad")+'">'+x.status+'<div class="muted">'+x.detail+'</div></span></div>').join('')+(na[0]?'<div class="muted" style="margin-top:8px">Latest maintenance: '+na[0].action_type+' · '+na[0].status+' · '+na[0].detail+'</div>':'')):'<div class="muted">NOAH is starting his first health cycle.</div>';}
 }catch(e){}
}
async function controlStatus(){
 if(!own())return;
 try{
  const d=await(await fetch(CTRL,{cache:"no-store",headers:hdr()})).json();if(!d.ok)throw new Error(d.error||"Control status failed");const x=d.result||{};
  $("autoToggle").classList.toggle("on",!!x.autonomous_enabled);$("deviceLockToggle").classList.toggle("on",!!x.owner_device_required);
  $("pairState").textContent=x.this_device_paired?"Paired until "+new Date(x.owner_session_expires_at).toLocaleString():"Not paired";$("pairBadge").textContent=x.this_device_paired?"PAIRED":"UNPAIRED";$("pairBadge").className="badge "+(x.this_device_paired?"live":"");
  $("pairBtn").style.display=x.this_device_paired?"none":"block";$("unpairBtn").style.display=x.this_device_paired?"block":"none";
  $("safetyData").innerHTML='<div class="row"><span>Live execution</span><b>'+(x.live_enabled?"ON":"OFF")+'</b></div><div class="row"><span>Mode</span><b>'+String(x.mode||"—").toUpperCase()+'</b></div><div class="row"><span>Kill switch</span><b>'+(x.kill_switch?"ARMED":"DISARMED")+'</b></div><div class="row"><span>Active owner devices</span><b>'+Number(x.active_owner_devices||0)+'</b></div>';
 }catch(e){$("ownerMsg").textContent=e.message||String(e)}
}
async function ctrl(action,payload={}){
 const res=await fetch(CTRL,{method:"POST",headers:{"content-type":"application/json",...hdr()},body:JSON.stringify({action,...payload})});const d=await res.json().catch(()=>({}));if(!d.ok)throw new Error(d.error||"Control action failed");return d.result;
}
$("unlock").onclick=()=>{const t=$("ownerToken").value.trim();if(!t){$("ownerMsg").textContent="Enter owner token first.";return}sessionStorage.setItem("moses_owner_token",t);$("ownerToken").value="";$("ownerMsg").textContent="Owner controls unlocked for this tab.";activity();controlStatus();loadPerformance();if(activeChartMint)loadTokenChart()};
$("lock").onclick=()=>{sessionStorage.removeItem("moses_owner_token");$("ownerMsg").textContent="Owner controls locked."};
$("autoToggle").onclick=async()=>{try{const on=!$("autoToggle").classList.contains("on");await ctrl("set_autonomous",{enabled:on});$("ownerMsg").textContent=on?"Autonomous mode enabled.":"Autonomous entries paused. JOSHUA remains available for position protection.";await controlStatus();await activity()}catch(e){$("ownerMsg").textContent=e.message}};
$("deviceLockToggle").onclick=async()=>{try{const on=!$("deviceLockToggle").classList.contains("on");await ctrl("set_owner_device_required",{enabled:on});await controlStatus()}catch(e){$("ownerMsg").textContent=e.message}};
$("pairBtn").onclick=async()=>{try{const x=await ctrl("pair_this_device",{label:"Owner Android"});localStorage.setItem("moses_owner_session",x.session_token);$("ownerMsg").textContent="This device is paired.";await controlStatus()}catch(e){$("ownerMsg").textContent=e.message}};
$("unpairBtn").onclick=async()=>{try{await ctrl("revoke_this_device");localStorage.removeItem("moses_owner_session");$("ownerMsg").textContent="This device is unpaired.";await controlStatus()}catch(e){$("ownerMsg").textContent=e.message}};
$("manualBuy").onclick=async()=>{const mint=$("manualMint").value.trim(),b=$("manualBuy");b.disabled=true;b.textContent="MOSES analyzing…";$("manualMsg").textContent="Running hard exitability and risk checks…";try{const x=await ctrl("manual_contract_buy",{mint,notional_usd:selectedSize});$("manualMsg").textContent="Submitted to MOSES. Order "+short(x&&x.order&&x.order.order_id||"")+".";$("manualMint").value="";await portfolio();await activity()}catch(e){$("manualMsg").textContent=e.message||String(e)}finally{b.disabled=false;b.textContent="Hand to MOSES"}};
portfolio();if(own()){activity();controlStatus();loadPerformance();if(activeChartMint)loadTokenChart()}setInterval(portfolio,10000);setInterval(()=>{if(own())activity()},5000);setInterval(()=>{if(own())controlStatus()},10000);setInterval(()=>{if(own())loadPerformance()},15000);setInterval(()=>{if(own()&&activeChartMint)loadTokenChart()},10000);
if("serviceWorker"in navigator)navigator.serviceWorker.register("moses-sw.js").catch(()=>{});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();dp=e;$("install").style.display="block"});$("install").onclick=async()=>{if(dp){dp.prompt();await dp.userChoice;dp=null;$("install").style.display="none"}};
